/**
* Top Speed 3
* Copyright 2003-2013 Playing in the Dark (http://playinginthedark.net)
* Code contributors: Davy Kager, Davy Loots and Leonard de Ruijter
* This program is distributed under the terms of the GNU General Public License version 3.
*/
#ifndef __RACING_TRACKDEFS_H__
#define __RACING_TRACKDEFS_H__

// NEVER INCLUDE THIS FILE IN A HEADER!!

/*
        straight        = 0,
        easyLeft        = 1,
        left            = 2,
        hardLeft        = 3,
        hairpinLeft     = 4,
        easyRight       = 5,
        right           = 6,
        hardRight       =  7,
        hairpinRight    = 8

        noNoise         = 0,
        crowd        = 1,
        ocean        = 2, 
        runway       = 3,
        clock        = 4,
        jet          = 5,
        thunder      = 6,
        pile         = 7,
        construction = 8,
        river        = 9,
        helicopter        = 10
        owl        = 11
*/

Track::Definition _trAmerica[] =
{
    { Track::straight, Track::asphalt, Track::noNoise,     40000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     30000 },
    { Track::left,          Track::asphalt, Track::noNoise,     50000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     80000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     30000 },
    { Track::left,          Track::asphalt, Track::noNoise,     50000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 }
};

Track::Definition _trAustria[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::hardLeft,    Track::asphalt, Track::noNoise,     30000 },
    { Track::hairpinLeft,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hairpinLeft,   Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     60000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     20000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 }
};

Track::Definition _trBelgium[] = 
{
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     30000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     30000 },
    { Track::straight, Track::asphalt, Track::noNoise,      7000 },
    { Track::left,          Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hairpinRight,  Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     20000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::right,         Track::asphalt, Track::noNoise,     25000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     10000 }
};

Track::Definition _trBrazil[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::hardRight,          Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::right,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::easyLeft,  Track::asphalt, Track::noNoise,     60000 },
    { Track::hardRight,         Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::left,  Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 }
};

Track::Definition _trChina[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::right,         Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::left,      Track::asphalt, Track::noNoise,     50000 },
    { Track::easyRight,   Track::asphalt, Track::noNoise,     60000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::hardLeft,      Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hardLeft,          Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
};

Track::Definition _trEngland[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::left,          Track::asphalt, Track::noNoise,     30000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hairpinRight,  Track::asphalt, Track::noNoise,     28000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::right,         Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::left,          Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 }
};

Track::Definition _trFinland[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::hairpinLeft,         Track::asphalt, Track::noNoise,     40000 },
    { Track::right,      Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     60000 },
    { Track::easyLeft,      Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::right,         Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::left,          Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
};

Track::Definition _trFrance[] = 
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::right,         Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hairpinLeft,   Track::asphalt, Track::noNoise,     60000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hardLeft,    Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::right,        Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 }
};

Track::Definition _trGermany[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::right,         Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::right,         Track::asphalt, Track::noNoise,     30000 },
    { Track::left,          Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     20000 },
    { Track::hardLeft,    Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 }
};

Track::Definition _trIreland[] = 
{
    { Track::straight,      Track::asphalt, Track::noNoise,     70000 },
    { Track::right,         Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     30000 },    
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     40000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     20000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::right,         Track::asphalt, Track::noNoise,     50000 },
    { Track::left,          Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     10000 }
};

Track::Definition _trItaly[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     25000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     25000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::hardLeft,    Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     30000 },
    { Track::left,          Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::right,         Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::right,         Track::asphalt, Track::noNoise,     70000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 }
};

Track::Definition _trNetherlands[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::left,          Track::asphalt, Track::noNoise,     20000 },
    { Track::straight,      Track::asphalt, Track::noNoise,      6000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     20000 },
    { Track::right,         Track::asphalt, Track::noNoise,     30000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     25000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::left,          Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     18000 },
    { Track::hardLeft,    Track::asphalt, Track::noNoise,     20000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     18000 }
};

Track::Definition _trPortugal[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::right,         Track::asphalt, Track::noNoise,     30000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     50000 },
    { Track::left,          Track::asphalt, Track::noNoise,     60000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
};

Track::Definition _trRussia[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::easyRight,         Track::asphalt, Track::noNoise,     40000 },
    { Track::left,      Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::easyRight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::left,         Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::easyLeft,          Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
};

Track::Definition _trSpain[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hardLeft,    Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::right,         Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     70000 },
    { Track::left,          Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::left,          Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 }
};

Track::Definition _trSweden[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     50000 },
    { Track::hardLeft,   Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::left,         Track::asphalt, Track::noNoise,     40000 },
    { Track::easyLeft,      Track::asphalt, Track::noNoise,     50000 },
    { Track::easyRight,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::right,   Track::asphalt, Track::noNoise,     40000 },
    { Track::easyRight,      Track::asphalt, Track::noNoise,     50000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
};

Track::Definition _trSwitserland[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::hairpinRight,   Track::asphalt, Track::noNoise,     31000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::right,         Track::asphalt, Track::noNoise,     30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::hardLeft,   Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     39000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::hardRight,          Track::asphalt, Track::noNoise,     40000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
};

Track::Definition _trAdvHills[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::left,          Track::gravel, Track::noNoise,      15000 },
    { Track::straight,      Track::gravel, Track::noNoise,      25000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      15000 },
    { Track::straight,      Track::gravel, Track::noNoise,      28000 },
    { Track::right,         Track::gravel, Track::noNoise,      22000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      15000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     15000 },
    { Track::left,          Track::asphalt, Track::noNoise,     25000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     19000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      17000 },
    { Track::right,         Track::gravel, Track::noNoise,      17000 },
    { Track::straight,      Track::gravel, Track::noNoise,      15000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      15000 },
    { Track::left,          Track::gravel, Track::noNoise,      10000 },
    { Track::hardLeft,    Track::gravel, Track::noNoise,      10000 },
    { Track::straight, Track::gravel, Track::crowd,      40000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      10000 },
    { Track::straight,      Track::snow, Track::noNoise,     45000 },
    { Track::easyRight,  Track::snow, Track::noNoise,     17500 },
    { Track::straight,      Track::snow, Track::noNoise,      9500 },
    { Track::easyLeft,   Track::snow, Track::noNoise,       9000 },
    { Track::right,         Track::gravel, Track::noNoise,      15000 },
    { Track::straight,      Track::gravel, Track::noNoise,      10000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      15000 },
    { Track::straight,      Track::gravel, Track::noNoise,       6000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      15000 },
    { Track::left,          Track::gravel, Track::noNoise,      15000 },
    { Track::straight,      Track::gravel, Track::noNoise,      11000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::straight, Track::asphalt, Track::crowd,     40000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     20000 },
    { Track::right,         Track::gravel, Track::noNoise,      20000 },
    { Track::straight,      Track::gravel, Track::noNoise,      15000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      20000 },
    { Track::straight,      Track::gravel, Track::noNoise,      20000 },
    { Track::left,          Track::gravel, Track::noNoise,      15000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      15000 },
    { Track::straight,      Track::gravel, Track::noNoise,      10000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     30000 },
    { Track::right,         Track::asphalt, Track::noNoise,     15000 },
    { Track::straight, Track::asphalt, Track::crowd,     40000 }
};

Track::Definition _trAdvCoast[] =
{
    { Track::straight,      Track::asphalt, Track::ocean,     40000 },
    { Track::easyRight,  Track::asphalt, Track::ocean,     25000 },
    { Track::left,          Track::asphalt, Track::ocean,     30000 },
    { Track::straight,      Track::gravel, Track::ocean,      19000 },
    { Track::left,          Track::gravel, Track::noNoise,      25000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      38000 },
    { Track::straight,      Track::gravel, Track::noNoise,      19000 },
    { Track::left,          Track::gravel, Track::noNoise,      19000 },
    { Track::straight,      Track::gravel, Track::noNoise,      22000 },
    { Track::straight,      Track::sand, Track::ocean,     21000 },
    { Track::left,          Track::sand, Track::ocean,     19000 },
    { Track::easyLeft,   Track::sand, Track::ocean,     20000 },
    { Track::straight, Track::sand, Track::ocean,     57000 },
    { Track::easyRight,  Track::sand, Track::ocean,      19000 },
    { Track::right,         Track::gravel, Track::noNoise,      16000 },
    { Track::left,          Track::gravel, Track::noNoise,      22000 },
    { Track::straight,      Track::gravel, Track::ocean,      35000 },
    { Track::right,         Track::gravel, Track::noNoise,      15000 },
    { Track::easyLeft,   Track::sand, Track::noNoise,     22000 },
    { Track::left,          Track::sand, Track::noNoise,     21000 },
    { Track::easyRight,  Track::sand, Track::noNoise,     13000 },
    { Track::hardLeft,    Track::sand, Track::noNoise,     15000 },
    { Track::straight,      Track::gravel, Track::ocean,     32000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      19000 },
    { Track::straight,      Track::gravel, Track::noNoise,      12000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      19000 },
    { Track::straight,      Track::gravel, Track::noNoise,      19000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      14000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      30000 },
    { Track::straight, Track::water, Track::ocean,     60000 },
    { Track::right,         Track::sand, Track::noNoise,     30000 },
    { Track::straight,      Track::sand, Track::noNoise,     20000 },
    { Track::easyLeft,   Track::sand, Track::noNoise,     30000 },
    { Track::straight,      Track::sand, Track::noNoise,     15000 },
    { Track::right,         Track::sand, Track::noNoise,     20000 },
    { Track::straight,      Track::gravel, Track::noNoise,      20000 },
    { Track::right,         Track::gravel, Track::noNoise,      15000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      15000 },
    { Track::straight, Track::gravel, Track::noNoise,      42000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      30000 },
    { Track::straight,      Track::asphalt, Track::ocean,     50000 }
};

Track::Definition _trAdvCountry[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     25000 },
    { Track::hardLeft,    Track::asphalt, Track::noNoise,     25000 },
    { Track::straight,      Track::gravel, Track::noNoise,      35000 },
    { Track::right,         Track::gravel, Track::noNoise,      25000 },
    { Track::straight,      Track::gravel, Track::noNoise,      35000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      30000 },
    { Track::straight,      Track::gravel, Track::river,      61000 },
    { Track::hardLeft,    Track::gravel, Track::noNoise,      17000 },
    { Track::straight,      Track::gravel, Track::noNoise,      25000 },
    { Track::left,          Track::gravel, Track::noNoise,      20000 },
    { Track::straight,      Track::water, Track::thunder,       31000 },
    { Track::straight,      Track::gravel, Track::noNoise,      28000 },
    { Track::right,         Track::gravel, Track::noNoise,      21000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     35000 },
    { Track::easyLeft,      Track::asphalt, Track::noNoise,     16000 },
    { Track::straight,      Track::water, Track::noNoise,       25000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     27000 },
    { Track::right,         Track::asphalt, Track::noNoise,     22000 },
    { Track::straight,      Track::gravel, Track::noNoise,      28000 },
    { Track::easyRight,     Track::gravel, Track::noNoise,      13000 },
    { Track::hairpinRight,  Track::gravel, Track::river,      21000 },
    { Track::straight, Track::water, Track::river,       48000 },
    { Track::left,          Track::gravel, Track::noNoise,      15000 },
    { Track::right,         Track::gravel, Track::noNoise,      12000 },
    { Track::straight,   Track::gravel, Track::thunder,      12000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     32000 },
    { Track::left,          Track::asphalt, Track::noNoise,     15000 },
    { Track::easyRight,     Track::asphalt, Track::noNoise,     18000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     24000 },
    { Track::easyRight,     Track::water, Track::noNoise,       30000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     20000 },
    { Track::hardRight,     Track::asphalt, Track::noNoise,     14000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     15000 },
    { Track::easyLeft,      Track::asphalt, Track::noNoise,     15000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     12000 },
    { Track::hairpinLeft,   Track::asphalt, Track::noNoise,     15000 },
    { Track::straight, Track::gravel, Track::noNoise,      35000 },
    { Track::right,         Track::gravel, Track::thunder,      21000 },
    { Track::straight,      Track::gravel, Track::river,     70000 }
};

Track::Definition _trAirport[] =
{
    { Track::straight,      Track::asphalt, Track::noNoise,     22000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     26000 },
    { Track::straight,      Track::gravel, Track::noNoise,      16000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      23000 },
    { Track::straight,      Track::gravel, Track::noNoise,      26000 },
    { Track::left,          Track::gravel, Track::noNoise,      28000 },
    { Track::easyRight,  Track::gravel, Track::noNoise,      17000 },
    { Track::straight,Track::asphalt, Track::runway,      6000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     46000 },
    { Track::right,         Track::asphalt, Track::noNoise,     21000 },
    { Track::left,          Track::asphalt, Track::noNoise,     18000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     16000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     27000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     16000 },
    { Track::hardRight,   Track::asphalt, Track::noNoise,     12000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     28000 },
    { Track::right,         Track::asphalt, Track::noNoise,     27000 },
    { Track::straight,Track::asphalt, Track::jet,      6000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     36000 },
    { Track::left,          Track::asphalt, Track::noNoise,     19000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     11000 },
    { Track::straight,      Track::asphalt, Track::noNoise,      7000 },
    { Track::hardRight,   Track::asphalt, Track::helicopter,     13000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     18000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     17000 },
    { Track::straight,      Track::asphalt, Track::noNoise,      6000 },
    { Track::left,          Track::asphalt, Track::noNoise,     12000 },
    { Track::hairpinRight,  Track::asphalt, Track::noNoise,     11000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     17000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     21000 },
    { Track::straight,Track::asphalt, Track::jet,      6000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     17000 },
    { Track::straight,      Track::gravel, Track::noNoise,      24000 },
    { Track::easyLeft,   Track::gravel, Track::noNoise,      17000 },
    { Track::straight,      Track::gravel, Track::noNoise,      17000 },
    { Track::left,          Track::gravel, Track::noNoise,      17000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     21000 },
    { Track::right,         Track::asphalt, Track::noNoise,     16000 },
    { Track::easyLeft,   Track::asphalt, Track::noNoise,     12000 },
    { Track::straight,      Track::asphalt, Track::helicopter,     30000 },
    { Track::easyRight,  Track::asphalt, Track::noNoise,     16000 },
    { Track::straight,      Track::asphalt, Track::noNoise,     40000 }
};

Track::Definition _trDesert[] =
{
    { Track::straight, Track::sand, Track::crowd, 150000 },
    { Track::easyLeft, Track::sand, Track::noNoise, 20000 },
    { Track::hardRight, Track::sand, Track::noNoise, 40000 },
    { Track::hardLeft, Track::sand, Track::noNoise, 30000 },
    { Track::hairpinLeft, Track::sand, Track::noNoise, 90000 },
    { Track::straight, Track::sand, Track::noNoise, 100000 },
    { Track::hardRight, Track::sand, Track::owl, 20000 },
    { Track::straight, Track::sand, Track::noNoise, 40000 },
    { Track::easyRight, Track::sand, Track::noNoise, 19000 },
    { Track::hardRight, Track::sand, Track::noNoise, 11111 },
    { Track::hardLeft, Track::sand, Track::noNoise, 40000 },
    { Track::easyLeft, Track::sand, Track::noNoise, 9000 },
    { Track::easyRight, Track::sand, Track::noNoise, 70000 },
    { Track::straight, Track::sand, Track::noNoise, 8000 },
    { Track::easyRight, Track::sand, Track::noNoise, 40000 },
    { Track::straight, Track::sand, Track::noNoise, 40000 },
    { Track::hardLeft, Track::sand, Track::owl, 10000 },
    { Track::easyLeft, Track::sand, Track::noNoise, 80000 },
    { Track::easyRight, Track::sand, Track::noNoise, 75000 },
    { Track::straight, Track::sand, Track::noNoise, 125000 },
    { Track::easyLeft, Track::sand, Track::noNoise, 10000 },
    { Track::straight, Track::sand, Track::noNoise, 18000 },
    { Track::straight, Track::sand, Track::jet, 5000 },
    { Track::straight, Track::sand, Track::noNoise, 40000 },
    { Track::hairpinRight, Track::sand, Track::noNoise, 46000 },
    { Track::easyRight, Track::sand, Track::owl, 12345 },
    { Track::straight, Track::sand, Track::noNoise, 10000 },
    { Track::hairpinRight, Track::sand, Track::noNoise, 40000 },
    { Track::hairpinLeft, Track::sand, Track::noNoise, 77777 },
    { Track::easyRight, Track::sand, Track::noNoise, 54321 },
    { Track::straight, Track::sand, Track::noNoise, 99999 },
    { Track::hairpinRight, Track::sand, Track::owl, 6000 },
    { Track::hardRight, Track::sand, Track::noNoise, 40000 },
    { Track::right, Track::sand, Track::noNoise, 40000 },
    { Track::easyRight, Track::sand, Track::noNoise, 10000 },
    { Track::easyLeft, Track::sand, Track::noNoise, 30000 },
    { Track::straight, Track::sand, Track::noNoise, 200000 },
    { Track::hardRight, Track::sand, Track::noNoise, 60000 },
    { Track::straight, Track::sand, Track::noNoise, 35000 },
    { Track::right, Track::sand, Track::noNoise, 80000 },
    { Track::straight, Track::sand, Track::owl, 8500 },
    { Track::easyLeft, Track::sand, Track::noNoise, 33333 },
    { Track::hairpinRight, Track::sand, Track::noNoise, 46000 },
    { Track::hardLeft, Track::sand, Track::noNoise, 60000 },
    { Track::hardRight, Track::sand, Track::noNoise, 40000 },
    { Track::straight, Track::sand, Track::noNoise, 25000 },
    { Track::hairpinRight, Track::sand, Track::noNoise, 42000 },
    { Track::straight, Track::sand, Track::noNoise, 90000 },
    { Track::hardRight, Track::sand, Track::noNoise, 20000 },
    { Track::easyLeft, Track::sand, Track::noNoise, 30000 },
    { Track::hairpinLeft, Track::sand, Track::noNoise, 95000 },
    { Track::straight, Track::sand, Track::noNoise, 500000 },
    { Track::easyRight, Track::sand, Track::owl, 6000 },
    { Track::right, Track::sand, Track::noNoise, 6000 },
    { Track::hardRight, Track::sand, Track::noNoise, 6000 },
    { Track::hairpinRight, Track::sand, Track::noNoise, 40000 },
    { Track::straight, Track::sand, Track::noNoise, 250000 },
    { Track::easyLeft, Track::sand, Track::owl, 5000 },
    { Track::left, Track::sand, Track::noNoise, 5000 },
    { Track::hardLeft, Track::sand, Track::noNoise, 5000 },
    { Track::hairpinLeft, Track::sand, Track::noNoise, 50000 },
    { Track::straight, Track::sand, Track::noNoise, 15000 },
    { Track::hardLeft, Track::sand, Track::noNoise, 40000 },
	{ Track::hairpinLeft, Track::sand, Track::noNoise, 20000 },
    { Track::straight, Track::sand, Track::noNoise, 30000 },
    { Track::hardRight, Track::sand, Track::owl, 7500 },
    { Track::straight, Track::sand, Track::noNoise, 100000 },
    { Track::hairpinLeft, Track::sand, Track::noNoise, 75000 },
    { Track::straight, Track::sand, Track::noNoise, 40000 },
    { Track::easyLeft, Track::sand, Track::noNoise, 10000 },
    { Track::hairpinRight, Track::sand, Track::noNoise, 60000 },
    { Track::hardLeft, Track::sand, Track::owl, 10000 },
    { Track::straight, Track::sand, Track::noNoise, 35000 },
    { Track::hardLeft, Track::sand, Track::noNoise, 33333 },
    { Track::straight, Track::sand, Track::noNoise, 5000 },
    { Track::hardLeft, Track::sand, Track::noNoise, 33333 },
    { Track::straight, Track::sand, Track::noNoise, 33333 },
    { Track::hardLeft, Track::sand, Track::noNoise, 33333 },
    { Track::straight, Track::sand, Track::noNoise, 33333 },
    { Track::hardLeft, Track::sand, Track::noNoise, 44444 },
    { Track::straight, Track::sand, Track::noNoise, 55555 },
    { Track::hardLeft, Track::sand, Track::noNoise, 33333 },
    { Track::straight, Track::sand, Track::owl, 22222 },
    { Track::hairpinRight, Track::sand, Track::noNoise, 100000 },
    { Track::hardRight, Track::sand, Track::noNoise, 30000 },
    { Track::right, Track::sand, Track::noNoise, 30000 },
    { Track::hardLeft, Track::sand, Track::noNoise, 66666 },
    { Track::straight, Track::sand, Track::noNoise, 666666 },
    { Track::straight, Track::sand, Track::owl, 10000 },
    { Track::straight, Track::sand, Track::noNoise, 10000 }
};

Track::Definition _trAdvRush[] =
{
    { Track::straight, Track::asphalt, Track::clock, 35000 },
    { Track::straight, Track::asphalt, Track::noNoise, 120000 },
    { Track::straight, Track::asphalt, Track::construction, 53000 },
    { Track::hardLeft, Track::asphalt, Track::construction, 70000 },
    { Track::straight, Track::asphalt, Track::noNoise, 30000 },
    { Track::hardLeft, Track::asphalt, Track::noNoise, 24000 },
    { Track::left, Track::asphalt, Track::noNoise, 30000 },
    { Track::hardLeft, Track::asphalt, Track::noNoise, 32000 },
    { Track::straight, Track::asphalt, Track::noNoise, 19000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 35000 },
    { Track::straight, Track::asphalt, Track::noNoise, 15000 },
    { Track::easyLeft, Track::asphalt, Track::noNoise, 52000 },
    { Track::left, Track::asphalt, Track::noNoise, 23000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 5000 },
    { Track::straight, Track::asphalt, Track::construction, 25000 },
    { Track::hardLeft, Track::asphalt, Track::noNoise, 20000 },
    { Track::straight, Track::asphalt, Track::noNoise, 100000 },
    { Track::straight, Track::asphalt, Track::pile, 85000 },
    { Track::easyLeft, Track::asphalt, Track::pile, 32000 },
    { Track::straight, Track::asphalt, Track::noNoise, 42000 },
    { Track::hardRight, Track::asphalt, Track::noNoise, 20000 },
    { Track::straight, Track::asphalt, Track::noNoise, 20000 },
    { Track::left, Track::asphalt, Track::noNoise, 23000 },
    { Track::straight, Track::asphalt, Track::noNoise, 21000 },
    { Track::easyLeft, Track::asphalt, Track::noNoise, 39000 },
    { Track::hardRight, Track::asphalt, Track::noNoise, 43000 },
    { Track::left, Track::asphalt, Track::noNoise, 38000 },
    { Track::straight, Track::asphalt, Track::noNoise, 50000 },
    { Track::straight, Track::asphalt, Track::construction, 69000 },
    { Track::straight, Track::asphalt, Track::clock, 38000 },
    { Track::left, Track::asphalt, Track::noNoise, 30000 },
    { Track::hardRight, Track::asphalt, Track::noNoise, 43000 },
    { Track::right, Track::asphalt, Track::noNoise, 30000 },
    { Track::straight, Track::asphalt, Track::noNoise, 10000 },
    { Track::straight, Track::asphalt, Track::construction, 40000 },
    { Track::straight, Track::asphalt, Track::clock, 76000 },
    { Track::hardRight, Track::asphalt, Track::noNoise, 30000 },
    { Track::hardLeft, Track::asphalt, Track::noNoise, 30000 },
    { Track::straight, Track::asphalt, Track::noNoise, 100000 },
    { Track::hardLeft, Track::asphalt, Track::noNoise, 34000 },
    { Track::straight, Track::asphalt, Track::clock, 100000 },
    { Track::straight, Track::asphalt, Track::construction, 20000 },
    { Track::left, Track::asphalt, Track::noNoise, 20000 },
    { Track::straight, Track::asphalt, Track::noNoise, 20000 },
    { Track::left, Track::asphalt, Track::noNoise, 20000 },
    { Track::straight, Track::asphalt, Track::noNoise, 10000 },
    { Track::straight, Track::asphalt, Track::clock, 6700 },
    { Track::straight, Track::asphalt, Track::noNoise, 82000 },
    { Track::left, Track::asphalt, Track::noNoise, 42000 },
    { Track::right, Track::asphalt, Track::noNoise, 30000 },
    { Track::straight, Track::asphalt, Track::clock, 130000 },
    { Track::left, Track::asphalt, Track::noNoise, 23000 },
    { Track::hardRight, Track::asphalt, Track::noNoise, 28000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 10000 },
    { Track::straight, Track::asphalt, Track::noNoise, 20000 },
    { Track::straight, Track::asphalt, Track::clock, 103000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 30000 },
    { Track::right, Track::asphalt, Track::noNoise, 34000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 34000 },
    { Track::straight, Track::asphalt, Track::clock, 5000 },
    { Track::easyRight, Track::asphalt, Track::clock, 34000 },
    { Track::left, Track::asphalt, Track::clock, 30000 },
    { Track::right, Track::asphalt, Track::clock, 30000 },
    { Track::left, Track::asphalt, Track::clock, 30000 },
    { Track::straight, Track::asphalt, Track::clock, 18000 },
    { Track::hardRight, Track::asphalt, Track::noNoise, 5000 },
    { Track::straight, Track::asphalt, Track::noNoise, 120000 },
    { Track::straight, Track::asphalt, Track::pile, 58000 },
    { Track::hardRight, Track::asphalt, Track::noNoise, 62000 },
    { Track::straight, Track::gravel, Track::noNoise, 21000 },
    { Track::straight, Track::gravel, Track::construction, 40000 },
    { Track::straight, Track::gravel, Track::construction, 50000 },
    { Track::straight, Track::asphalt, Track::noNoise, 100000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 60000 },
    { Track::right, Track::asphalt, Track::noNoise, 45000 },
    { Track::left, Track::asphalt, Track::noNoise, 52000 },
    { Track::easyLeft, Track::asphalt, Track::noNoise, 31000 },
    { Track::straight, Track::asphalt, Track::construction, 130000 },
    { Track::easyLeft, Track::asphalt, Track::pile, 26000 },
    { Track::easyRight, Track::asphalt, Track::pile, 30000 },
    { Track::left, Track::asphalt, Track::pile, 30000 },
    { Track::right, Track::asphalt, Track::pile, 31000 },
    { Track::left, Track::asphalt, Track::pile, 30000 },
    { Track::straight, Track::asphalt, Track::pile, 23000 },
    { Track::left, Track::asphalt, Track::pile, 32000 },
    { Track::straight, Track::asphalt, Track::noNoise, 35000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 43000 },
    { Track::right, Track::asphalt, Track::noNoise, 34000 },
    { Track::left, Track::asphalt, Track::clock, 100000 },
    { Track::straight, Track::asphalt, Track::clock, 16000 },
    { Track::hardRight, Track::asphalt, Track::clock, 100000 },
    { Track::straight, Track::gravel, Track::clock, 80000 },
    { Track::straight, Track::gravel, Track::noNoise, 100000 },
    { Track::left, Track::asphalt, Track::noNoise, 13000 },
    { Track::hardLeft, Track::asphalt, Track::noNoise, 100000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 50000 },
    { Track::right, Track::asphalt, Track::noNoise, 50000 },
    { Track::easyRight, Track::asphalt, Track::noNoise, 30000 },
    { Track::easyLeft, Track::asphalt, Track::noNoise, 41000 },
    { Track::straight, Track::gravel, Track::noNoise, 100000 },
    { Track::straight, Track::asphalt, Track::noNoise, 100000 },
    { Track::straight, Track::asphalt, Track::pile, 70000 },
    { Track::straight, Track::asphalt, Track::construction, 20000 },
    { Track::straight, Track::asphalt, Track::clock, 100000 }
};

Track::Definition _trAdvEscape[] =
{
    { Track::straight, Track::snow, Track::noNoise, 50000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 38000 },
    { Track::easyRight, Track::snow, Track::noNoise, 30000 },
    { Track::left, Track::snow, Track::noNoise, 10000 },
    { Track::straight, Track::snow, Track::noNoise, 20000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 20000 },
    { Track::straight, Track::snow, Track::noNoise, 20000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 68000 },
    { Track::easyRight, Track::snow, Track::noNoise, 6000 },
    { Track::straight, Track::snow, Track::noNoise, 103000 },
    { Track::left, Track::snow, Track::noNoise, 20000 },
    { Track::right, Track::snow, Track::noNoise, 30000 },
    { Track::left, Track::snow, Track::noNoise, 130000 },
    { Track::straight, Track::snow, Track::noNoise, 51000 },
    { Track::easyRight, Track::snow, Track::noNoise, 40000 },
    { Track::right, Track::snow, Track::noNoise, 5000 },
    { Track::straight, Track::snow, Track::noNoise, 180000 },
    { Track::easyRight, Track::snow, Track::noNoise, 139000 },
    { Track::left, Track::snow, Track::noNoise, 25000 },
    { Track::right, Track::snow, Track::noNoise, 35000 },
    { Track::straight, Track::snow, Track::noNoise, 10000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 20000 },
    { Track::straight, Track::snow, Track::noNoise, 83500 },
    { Track::easyLeft, Track::snow, Track::noNoise, 25000 },
    { Track::straight, Track::snow, Track::noNoise, 30000 },
    { Track::easyRight, Track::snow, Track::noNoise, 37000 },
    { Track::straight, Track::snow, Track::noNoise, 58000 },
    { Track::right, Track::snow, Track::noNoise, 15000 },
    { Track::left, Track::snow, Track::noNoise, 13000 },
    { Track::straight, Track::snow, Track::noNoise, 10000 },
    { Track::right, Track::snow, Track::noNoise, 5000 },
    { Track::straight, Track::snow, Track::noNoise, 10000 },
    { Track::easyRight, Track::snow, Track::noNoise, 60000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 30000 },
    { Track::left, Track::snow, Track::noNoise, 53000 },
    { Track::straight, Track::snow, Track::noNoise, 38000 },
    { Track::easyRight, Track::snow, Track::noNoise, 34000 },
    { Track::right, Track::snow, Track::noNoise, 35000 },
    { Track::left, Track::snow, Track::noNoise, 80500 },
    { Track::straight, Track::snow, Track::noNoise, 35000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 10000 },
    { Track::left, Track::snow, Track::noNoise, 80000 },
    { Track::straight, Track::snow, Track::noNoise, 100000 },
    { Track::left, Track::snow, Track::noNoise, 90000 },
    { Track::straight, Track::snow, Track::noNoise, 30000 },
    { Track::right, Track::snow, Track::noNoise, 75000 },
    { Track::easyRight, Track::snow, Track::noNoise, 100000 },
    { Track::straight, Track::snow, Track::noNoise, 18000 },
    { Track::left, Track::snow, Track::noNoise, 50000 },
    { Track::right, Track::snow, Track::noNoise, 35000 },
    { Track::left, Track::snow, Track::noNoise, 13000 },
    { Track::straight, Track::snow, Track::noNoise, 60000 },
    { Track::easyRight, Track::snow, Track::noNoise, 100000 },
    { Track::straight, Track::snow, Track::noNoise, 58000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 10000 },
    { Track::left, Track::snow, Track::noNoise, 100000 },
    { Track::easyRight, Track::snow, Track::noNoise, 78000 },
    { Track::straight, Track::snow, Track::noNoise, 6000 },
    { Track::easyRight, Track::snow, Track::noNoise, 32000 },
    { Track::left, Track::snow, Track::noNoise, 23000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 50000 },
    { Track::easyRight, Track::snow, Track::noNoise, 17000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 30000 },
    { Track::left, Track::snow, Track::noNoise, 22000 },
    { Track::straight, Track::snow, Track::noNoise, 35000 },
    { Track::left, Track::snow, Track::noNoise, 30000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 30000 },
    { Track::left, Track::snow, Track::noNoise, 30000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 58000 },
    { Track::left, Track::snow, Track::noNoise, 10000 },
    { Track::straight, Track::snow, Track::noNoise, 59000 },
    { Track::right, Track::snow, Track::noNoise, 70000 },
    { Track::straight, Track::snow, Track::crowd, 52000 },
    { Track::easyLeft, Track::snow, Track::crowd, 23000 },
    { Track::left, Track::snow, Track::crowd, 23000 },
    { Track::easyRight, Track::snow, Track::crowd, 37000 },
    { Track::right, Track::snow, Track::crowd, 100000 },
    { Track::straight, Track::snow, Track::noNoise, 28000 },
    { Track::easyLeft, Track::snow, Track::noNoise, 9200 },
    { Track::straight, Track::snow, Track::noNoise, 82000 },
    { Track::right, Track::snow, Track::noNoise, 35000 },
    { Track::straight, Track::snow, Track::river, 52000 },
    { Track::easyRight, Track::snow, Track::river, 30000 },
	{ Track::right, Track::snow, Track::river, 30000 },
    { Track::easyRight, Track::snow, Track::river, 35000 },
    { Track::straight, Track::snow, Track::river, 20000 },
    { Track::right, Track::snow, Track::river, 47000 },
    { Track::straight, Track::water, Track::river, 85000 }
};

#endif /* __RACING_TRACKDEFS_H__ */
